# Cloud Build configuration file
steps:
  # Step 1: Set up the Compute Engine instance
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create Compute Engine Instance'
    args:
      - 'compute'
      - 'instances'
      - 'create'
      - 'my-compute-instance23'  # Your instance name
      - '--zone=us-central1-a'     # Your instance zone
      - '--machine-type=e2-medium' # Your machine type
      - '--image-family=windows-2019'  # OS image family (Windows Server 2019)
      - '--image-project=windows-cloud'  # Image project (Windows Cloud)
      - '--boot-disk-size=50GB'  # Boot disk size (Standard 50 GB)
      - '--boot-disk-type=pd-standard'  # Standard HDD disk type
      - '--tags=http-server,https-server'  # Optional: Add firewall rules if needed

  # Step 2: Add the admin user and set the password
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Set Admin Username and Password'
    args:
      - 'compute'
      - 'reset-windows-password'
      - '--zone=us-central1-a'
      - '--user=bhowmick_partha1998'  # Your username
      - '--instance=my-compute-instance24'  # Your instance name

# Specify the default service account for this build
serviceAccount: '878866643834-compute@developer.gserviceaccount.com'

# Specify the logs bucket (replace with your actual bucket name)
logs_bucket: 'gs://gcstestex'

# Optional: Define a timeout (adjust if necessary)
timeout: '1200s'  # 20 minutes

# Optional: Define any substitutions for reusable configuration
substitutions:
  _INSTANCE_NAME: 'my-compute-instance22'  # Your instance name
