# Cloud Build configuration file
steps:
  # Step 1: Set up the Compute Engine instance
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create Compute Engine Instance'
    args:
      - 'compute'
      - 'instances'
      - 'create'
      - 'my-gcstest-instance5'  # Your instance name
      - '--zone=us-central1-f'  # Your instance zone
      - '--machine-type=n1-standard-2'  # Machine type (2 vCPUs, 7.5 GB RAM)
      - '--image-family=windows-2022'  # OS image family (Windows Server 2022)
      - '--image-project=windows-cloud'  # Image project (Windows Cloud)
      - '--boot-disk-size=50GB'  # Boot disk size (Standard 50 GB)
      - '--boot-disk-type=pd-standard'  # Standard HDD disk type
      - '--tags=http-server,https-server'  # Optional: Add firewall rules if needed

  # Step 2: Add the admin user and set the password
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Set Admin Username and Password'
    args:
      - 'compute'
      - 'reset-windows-password'
      - '--zone=us-central1-f'
      - '--user=testgcpnow'  # Your admin username
      - '--instance=my-gcstest-instance5'  # Your instance name

# Specify the default service account for this build
serviceAccount: '878866643834-compute@developer.gserviceaccount.com'

# Specify the logs bucket (replace with your actual bucket name)
logs_bucket: 'gs://gcstestex'  # Replace with your logs bucket name

# Optional: Define a timeout (adjust if necessary)
timeout: '1200s'  # 20 minutes

# Optional: Define any substitutions for reusable configuration
substitutions:
  _INSTANCE_NAME: 'my-gcstest-instance5'  # Your instance name
