steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create Compute Engine Instance'
    args:
      - 'compute'
      - 'instances'
      - 'create'
      - 'my-windows-instance45'
      - '--zone=us-central1-a'
      - '--machine-type=n1-standard-2'
      - '--image-family=windows-2019'
      - '--image-project=windows-cloud'
      - '--boot-disk-size=50GB'
      - '--boot-disk-type=pd-standard'
      # Add startup script to create user
      - '--metadata=windows-startup-script-ps1=Add-LocalUser -Name "admin_user" -Password (ConvertTo-SecureString "AdminPassword123!" -AsPlainText -Force); Add-LocalGroupMember -Group "Administrators" -Member "admin_user"'
      # Enable serial port for troubleshooting
      - '--metadata=serial-port-enable=1'
      # Set tags for firewall rules (http, https, and RDP)
      - '--tags=http-server,https-server,rdp-server'

  # Add firewall rule to allow RDP and HTTP/HTTPS access
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Add Firewall Rule'
    args:
      - 'compute'
      - 'firewall-rules'
      - 'create'
      - 'allow-rdp-http-access'
      - '--direction=INGRESS'
      - '--priority=1000'
      - '--network=default'
      - '--action=ALLOW'
      - '--rules=tcp:3389,tcp:80,tcp:443'
      - '--source-ranges=0.0.0.0/0'
      - '--target-tags=rdp-server,http-server,https-server'

serviceAccount: '978741093453-compute@developer.gserviceaccount.com'
logsBucket: 'gs://gcstestexx'
timeout: '1200s'

substitutions:
  _INSTANCE_NAME: 'my-windows-instance45'

