steps:
  # Step 1: Set up the Compute Engine instance
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create Compute Engine Instance'
    args:
      - 'compute'
      - 'instances'
      - 'create'
      - 'gcstest-55'  # Your instance name
      - '--zone=us-central1-f'   # Your instance zone
      - '--machine-type=n1-standard-2'  # Your machine type
      - '--image-family=windows-2022'  # OS image family (Windows Server 2022)
      - '--image-project=windows-cloud'  # Image project (Windows Cloud)
      - '--boot-disk-size=50GB'  # Boot disk size (Standard 50 GB)
      - '--boot-disk-type=pd-standard'  # Standard HDD disk type
      - '--tags=http-server,https-server'  # Optional: Add firewall rules if needed

  # Step 2: Add the admin user and set the password
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Set Admin Username and Password'
    args:
      - 'compute'
      - 'reset-windows-password'
      - '--zone=us-central1-f'
      - '--user=testgcpnow'  # Your username
      - '--instance=gcstest-55'  # Your instance name

# Optional: Define a timeout (adjust if necessary)
timeout: '1200s'  # 20 minutes

# Specify the service account if required
serviceAccount: '878866643834-compute@developer.gserviceaccount.com'

# Define your logs bucket
logs_bucket: 'gs://gcstestex'  # Replace with your logs bucket

# Optional: Define any substitutions for reusable configuration
substitutions:
  _INSTANCE_NAME: 'gcstest-55'  # Your instance name

# Optional: Specify triggers for automatic builds
trigger:
  - branch: '^main$'

