steps:
  # Step 1: Set up the Compute Engine instance
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create Compute Engine Instance'
    args:
      - 'compute'
      - 'instances'
      - 'create'
      - 'my-compute-instance20'
      - '--zone=us-central1-a'
      - '--machine-type=n1-standard-2'
      - '--image-family=windows-2019'
      - '--image-project=windows-cloud'
      - '--boot-disk-size=50GB'
      - '--boot-disk-type=pd-standard'
      - '--tags=http-server,https-server'

  # Step 2: Add the admin user and set the password
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Set Admin User'
    args:
      - 'compute'
      - 'instances'
      - 'add-metadata'
      - 'my-compute-instance20'
      - '--zone=us-central1-a'
      - '--metadata'
      - 'windows-password=7:jS[N?LdUSTjp\', 'username=bhowmick_partha1999'

# Specify the default service account for this build
serviceAccount: '878866643834-compute@developer.gserviceaccount.com'
logs_bucket: 'gs://gcstestex'
timeout: '1200s'
substitutions:
  _INSTANCE_NAME: 'my-compute-instance20'

