steps:
  # Step 1: Create the Compute Engine instance with a startup script
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create Compute Engine Instance'
    args:
      - 'compute'
      - 'instances'
      - 'create'
      - 'my-compute-instance23'
      - '--zone=us-central1-a'
      - '--machine-type=n1-standard-2'
      - '--image-family=windows-2019'
      - '--image-project=windows-cloud'
      - '--boot-disk-size=50GB'
      - '--boot-disk-type=pd-standard'
      - '--metadata=windows-startup-script-ps1=Add-LocalUser -Name "bhowmick_partha19988" -Password (ConvertTo-SecureString "MySecurePassword123" -AsPlainText -Force); Add-LocalGroupMember -Group "Administrators" -Member "bhowmick_partha19988"'
      - '--tags=http-server,https-server'

# Specify the default service account for this build
serviceAccount: '878866643834-compute@developer.gserviceaccount.com'
logs_bucket: 'gs://gcstestex'
timeout: '1200s'
substitutions:
  _INSTANCE_NAME: 'my-compute-instance23'
