steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create Compute Engine Instance'
    args:
      - 'compute'
      - 'instances'
      - 'create'
      - 'my-windows-instance99'  # Instance name
      - '--zone=us-central1-a'   # Zone
      - '--machine-type=n1-standard-2'  # Machine type
      - '--image-family=windows-2019'   # Windows image
      - '--image-project=windows-cloud' # Project with Windows images
      - '--boot-disk-size=50GB'         # Boot disk size
      - '--boot-disk-type=pd-standard'  # Disk type
      - '--tags=http-server,https-server'  # Firewall tags
      - '--metadata=windows-startup-script-ps1=Add-LocalUser -Name "admin_user" -Password (ConvertTo-SecureString "AdminPassword123!" -AsPlainText -Force); Add-LocalGroupMember -Group "Administrators" -Member "admin_user",enable-oslogin=false'  # Combine metadata keys

serviceAccount: '978741093453-compute@developer.gserviceaccount.com'  # Service account for the instance
logsBucket: 'gs://gcstestexx'  # Log bucket
timeout: '1200s'

substitutions:
  _INSTANCE_NAME: 'my-windows-instance99'  # Optional substitution

